<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Livre extends \App\Entity\Livre implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'ISBN' => [parent::class, 'ISBN', null],
        "\0".parent::class."\0".'auteur' => [parent::class, 'auteur', null],
        "\0".parent::class."\0".'disponible' => [parent::class, 'disponible', null],
        "\0".parent::class."\0".'emprunts' => [parent::class, 'emprunts', null],
        "\0".parent::class."\0".'genre' => [parent::class, 'genre', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        'ISBN' => [parent::class, 'ISBN', null],
        'auteur' => [parent::class, 'auteur', null],
        'disponible' => [parent::class, 'disponible', null],
        'emprunts' => [parent::class, 'emprunts', null],
        'genre' => [parent::class, 'genre', null],
        'id' => [parent::class, 'id', null],
        'titre' => [parent::class, 'titre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
