<?php

namespace ContainerZSQhMSx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuteurControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bUeqAgj.App\Controller\AuteurController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.bUeqAgj'] ?? $container->load('get_ServiceLocator_BUeqAgjService'));

        if (isset($container->privates['.service_locator.bUeqAgj.App\\Controller\\AuteurController::edit()'])) {
            return $container->privates['.service_locator.bUeqAgj.App\\Controller\\AuteurController::edit()'];
        }

        return $container->privates['.service_locator.bUeqAgj.App\\Controller\\AuteurController::edit()'] = $a->withContext('App\\Controller\\AuteurController::edit()', $container);
    }
}
