<?php

namespace ContainerZSQhMSx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuteur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.knYhce5.App\Entity\Auteur' shared service.
     *
     * @return \App\Entity\Auteur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.knYhce5": it needs an instance of "App\\Entity\\Auteur" but this type has been excluded in "config/services.yaml".');
    }
}
