<?php

namespace ContainerZSQhMSx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmpruntControllerreturnBookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3M3byzo.App\Controller\EmpruntController::returnBook()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3M3byzo.App\\Controller\\EmpruntController::returnBook()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emprunt' => ['privates', '.errored..service_locator.3M3byzo.App\\Entity\\Emprunt', NULL, 'Cannot autowire service ".service_locator.3M3byzo": it needs an instance of "App\\Entity\\Emprunt" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'emprunt' => 'App\\Entity\\Emprunt',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\EmpruntController::returnBook()', $container);
    }
}
