<?php

namespace ContainerZSQhMSx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenreControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2Z1ymMW.App\Controller\GenreController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.2Z1ymMW'] ?? $container->load('get_ServiceLocator_2Z1ymMWService'));

        if (isset($container->privates['.service_locator.2Z1ymMW.App\\Controller\\GenreController::edit()'])) {
            return $container->privates['.service_locator.2Z1ymMW.App\\Controller\\GenreController::edit()'];
        }

        return $container->privates['.service_locator.2Z1ymMW.App\\Controller\\GenreController::edit()'] = $a->withContext('App\\Controller\\GenreController::edit()', $container);
    }
}
