<?php

namespace ContainerZSQhMSx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivre2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VS.1o9e.App\Entity\Livre' shared service.
     *
     * @return \App\Entity\Livre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VS.1o9e": it needs an instance of "App\\Entity\\Livre" but this type has been excluded in "config/services.yaml".');
    }
}
