<?php

namespace ContainerNqAXRpO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HaMucvRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HaMucvR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HaMucvR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuteurController::index' => ['privates', '.service_locator.X1TTRt9.App\\Controller\\AuteurController::index()', 'getAuteurControllerindexService', true],
            'App\\Controller\\AuteurController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AuteurController::new()', 'getAuteurControllernewService', true],
            'App\\Controller\\AuteurController::show' => ['privates', '.service_locator.knYhce5.App\\Controller\\AuteurController::show()', 'getAuteurControllershowService', true],
            'App\\Controller\\AuteurController::edit' => ['privates', '.service_locator.bUeqAgj.App\\Controller\\AuteurController::edit()', 'getAuteurControllereditService', true],
            'App\\Controller\\AuteurController::delete' => ['privates', '.service_locator.bUeqAgj.App\\Controller\\AuteurController::delete()', 'getAuteurControllerdeleteService', true],
            'App\\Controller\\EmpruntController::borrowBook' => ['privates', '.service_locator.nXhIcKl.App\\Controller\\EmpruntController::borrowBook()', 'getEmpruntControllerborrowBookService', true],
            'App\\Controller\\EmpruntController::returnBook' => ['privates', '.service_locator.3M3byzo.App\\Controller\\EmpruntController::returnBook()', 'getEmpruntControllerreturnBookService', true],
            'App\\Controller\\GenreController::index' => ['privates', '.service_locator.wjjxo8X.App\\Controller\\GenreController::index()', 'getGenreControllerindexService', true],
            'App\\Controller\\GenreController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\GenreController::new()', 'getGenreControllernewService', true],
            'App\\Controller\\GenreController::show' => ['privates', '.service_locator.DdvBgQL.App\\Controller\\GenreController::show()', 'getGenreControllershowService', true],
            'App\\Controller\\GenreController::edit' => ['privates', '.service_locator.2Z1ymMW.App\\Controller\\GenreController::edit()', 'getGenreControllereditService', true],
            'App\\Controller\\GenreController::delete' => ['privates', '.service_locator.2Z1ymMW.App\\Controller\\GenreController::delete()', 'getGenreControllerdeleteService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.wIBhm9E.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\LivreController::index' => ['privates', '.service_locator.wIBhm9E.App\\Controller\\LivreController::index()', 'getLivreControllerindexService', true],
            'App\\Controller\\LivreController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\LivreController::new()', 'getLivreControllernewService', true],
            'App\\Controller\\LivreController::show' => ['privates', '.service_locator.21cI76b.App\\Controller\\LivreController::show()', 'getLivreControllershowService', true],
            'App\\Controller\\LivreController::edit' => ['privates', '.service_locator.VS.1o9e.App\\Controller\\LivreController::edit()', 'getLivreControllereditService', true],
            'App\\Controller\\LivreController::delete' => ['privates', '.service_locator.VS.1o9e.App\\Controller\\LivreController::delete()', 'getLivreControllerdeleteService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SearchController::index' => ['privates', '.service_locator.wIBhm9E.App\\Controller\\SearchController::index()', 'getSearchControllerindexService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\AuteurController:index' => ['privates', '.service_locator.X1TTRt9.App\\Controller\\AuteurController::index()', 'getAuteurControllerindexService', true],
            'App\\Controller\\AuteurController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\AuteurController::new()', 'getAuteurControllernewService', true],
            'App\\Controller\\AuteurController:show' => ['privates', '.service_locator.knYhce5.App\\Controller\\AuteurController::show()', 'getAuteurControllershowService', true],
            'App\\Controller\\AuteurController:edit' => ['privates', '.service_locator.bUeqAgj.App\\Controller\\AuteurController::edit()', 'getAuteurControllereditService', true],
            'App\\Controller\\AuteurController:delete' => ['privates', '.service_locator.bUeqAgj.App\\Controller\\AuteurController::delete()', 'getAuteurControllerdeleteService', true],
            'App\\Controller\\EmpruntController:borrowBook' => ['privates', '.service_locator.nXhIcKl.App\\Controller\\EmpruntController::borrowBook()', 'getEmpruntControllerborrowBookService', true],
            'App\\Controller\\EmpruntController:returnBook' => ['privates', '.service_locator.3M3byzo.App\\Controller\\EmpruntController::returnBook()', 'getEmpruntControllerreturnBookService', true],
            'App\\Controller\\GenreController:index' => ['privates', '.service_locator.wjjxo8X.App\\Controller\\GenreController::index()', 'getGenreControllerindexService', true],
            'App\\Controller\\GenreController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\GenreController::new()', 'getGenreControllernewService', true],
            'App\\Controller\\GenreController:show' => ['privates', '.service_locator.DdvBgQL.App\\Controller\\GenreController::show()', 'getGenreControllershowService', true],
            'App\\Controller\\GenreController:edit' => ['privates', '.service_locator.2Z1ymMW.App\\Controller\\GenreController::edit()', 'getGenreControllereditService', true],
            'App\\Controller\\GenreController:delete' => ['privates', '.service_locator.2Z1ymMW.App\\Controller\\GenreController::delete()', 'getGenreControllerdeleteService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.wIBhm9E.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\LivreController:index' => ['privates', '.service_locator.wIBhm9E.App\\Controller\\LivreController::index()', 'getLivreControllerindexService', true],
            'App\\Controller\\LivreController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\LivreController::new()', 'getLivreControllernewService', true],
            'App\\Controller\\LivreController:show' => ['privates', '.service_locator.21cI76b.App\\Controller\\LivreController::show()', 'getLivreControllershowService', true],
            'App\\Controller\\LivreController:edit' => ['privates', '.service_locator.VS.1o9e.App\\Controller\\LivreController::edit()', 'getLivreControllereditService', true],
            'App\\Controller\\LivreController:delete' => ['privates', '.service_locator.VS.1o9e.App\\Controller\\LivreController::delete()', 'getLivreControllerdeleteService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\SearchController:index' => ['privates', '.service_locator.wIBhm9E.App\\Controller\\SearchController::index()', 'getSearchControllerindexService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AuteurController::index' => '?',
            'App\\Controller\\AuteurController::new' => '?',
            'App\\Controller\\AuteurController::show' => '?',
            'App\\Controller\\AuteurController::edit' => '?',
            'App\\Controller\\AuteurController::delete' => '?',
            'App\\Controller\\EmpruntController::borrowBook' => '?',
            'App\\Controller\\EmpruntController::returnBook' => '?',
            'App\\Controller\\GenreController::index' => '?',
            'App\\Controller\\GenreController::new' => '?',
            'App\\Controller\\GenreController::show' => '?',
            'App\\Controller\\GenreController::edit' => '?',
            'App\\Controller\\GenreController::delete' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\LivreController::index' => '?',
            'App\\Controller\\LivreController::new' => '?',
            'App\\Controller\\LivreController::show' => '?',
            'App\\Controller\\LivreController::edit' => '?',
            'App\\Controller\\LivreController::delete' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SearchController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AuteurController:index' => '?',
            'App\\Controller\\AuteurController:new' => '?',
            'App\\Controller\\AuteurController:show' => '?',
            'App\\Controller\\AuteurController:edit' => '?',
            'App\\Controller\\AuteurController:delete' => '?',
            'App\\Controller\\EmpruntController:borrowBook' => '?',
            'App\\Controller\\EmpruntController:returnBook' => '?',
            'App\\Controller\\GenreController:index' => '?',
            'App\\Controller\\GenreController:new' => '?',
            'App\\Controller\\GenreController:show' => '?',
            'App\\Controller\\GenreController:edit' => '?',
            'App\\Controller\\GenreController:delete' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\LivreController:index' => '?',
            'App\\Controller\\LivreController:new' => '?',
            'App\\Controller\\LivreController:show' => '?',
            'App\\Controller\\LivreController:edit' => '?',
            'App\\Controller\\LivreController:delete' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SearchController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
