<?php

namespace ContainerNqAXRpO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VS_1o9eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VS.1o9e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VS.1o9e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'livre' => ['privates', '.errored..service_locator.VS.1o9e.App\\Entity\\Livre', NULL, 'Cannot autowire service ".service_locator.VS.1o9e": it needs an instance of "App\\Entity\\Livre" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'livre' => 'App\\Entity\\Livre',
            'entityManager' => '?',
        ]);
    }
}
