<?php

namespace ContainerNqAXRpO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuteurControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X1TTRt9.App\Controller\AuteurController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X1TTRt9.App\\Controller\\AuteurController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'auteurRepository' => ['privates', 'App\\Repository\\AuteurRepository', 'getAuteurRepositoryService', true],
        ], [
            'auteurRepository' => 'App\\Repository\\AuteurRepository',
        ]))->withContext('App\\Controller\\AuteurController::index()', $container);
    }
}
