<?php

namespace ContainerNqAXRpO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuteurControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.knYhce5.App\Controller\AuteurController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.knYhce5.App\\Controller\\AuteurController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'auteur' => ['privates', '.errored..service_locator.knYhce5.App\\Entity\\Auteur', NULL, 'Cannot autowire service ".service_locator.knYhce5": it needs an instance of "App\\Entity\\Auteur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'auteur' => 'App\\Entity\\Auteur',
        ]))->withContext('App\\Controller\\AuteurController::show()', $container);
    }
}
